<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="user_story_14_main_user_story_13_main_apply_create" nsURI="http://cdapackage/user_story_14_main/user_story_13_main_apply_create/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|2|_|7|:Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;hold&quot;->  _ &quot;hold&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_13_main_apply_create_user_story_14_main" nsURI="http://cdapackage/user_story_13_main_apply_create/user_story_14_main/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|7|_|2|:Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;hold&quot;->  _ &quot;hold&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
