<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="user_story_10_main_perform_delete_user_story_10_main_perform_preserve"
    nsURI="http://cdapackage/user_story_10_main_perform_delete/user_story_10_main_perform_preserve/DeleteConflictReason"
    nsPrefix="CDAPackage">
  <eClassifiers xsi:type="ecore:EClass" name="#|3|_|6|:Action#">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;perform&quot; _ &quot;perform&quot;"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#//%23|2|_|7|%3AEntity%23"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="|0|_|4|:Persona">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;staff member&quot; _ &quot;staff member&quot;"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#//%23|3|_|6|%3AAction%23"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="#|2|_|7|:Entity#">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;completeness review&quot;->  _ &quot;completeness review&quot;"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
